workflows:
  ios-workflow:
    name: iOS Build Workflow
    environment:
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "com.anycallmobile.anycallmobile_trainingcenter" # Replace with your bundle ID
    scripts:
      - name: Install Flutter dependencies
        script: flutter pub get
      - name: Build IPA
        script: flutter build ipa --release --export-options-plist=ios/ExportOptions.plist
    artifacts:
      - build/ios/ipa/*.ipa