workflows:
  ios-unsigned:
    name: iOS Unsigned Build
    environment:
      flutter: stable
      xcode: 15.2
      cocoapods: default
    scripts:
      - name: Clean Flutter
        script: |
          flutter clean
          rm -rf ios/Pods ios/Podfile.lock pubspec.lock .dart_tool .packages build

      - name: Get dependencies
        script: flutter pub get

      - name: Build iOS frameworks (no code signing)
        script: flutter build ios --release --no-codesign

      - name: CocoaPods install
        script: |
          cd ios
          pod install --repo-update
          cd ..

      - name: Build IPA unsigned
        script: flutter build ipa --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa
