workflows:
  ios-unsigned:
    name: iOS Unsigned Build
    environment:
      flutter: stable
      xcode: 15.2
      cocoapods: default
    scripts:
      - name: Flutter clean and recreate ios folder
        script: |
          flutter clean
          rm -rf ios/Pods ios/Podfile.lock ios/.symlinks ios/Flutter
          rm -rf ios
          flutter create .
          flutter pub get

      - name: Restore Runner backup (if you have it)
        script: |
          # If you backed up Runner, copy it back here
          # cp -r backup/Runner ios/

      - name: Install CocoaPods via Homebrew (forced update)
        script: |
          brew install cocoapods || brew link --overwrite cocoapods
          pod setup

      - name: Install pods
        script: |
          cd ios
          pod install --repo-update
          cd ..

      - name: Build IPA (unsigned)
        script: flutter build ipa --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
