workflows:
  ios-unsigned:
    name: iOS Unsigned IPA Build
    environment:
      flutter: stable
      xcode: 15.2
      cocoapods: 1.16.2  # Use recommended CocoaPods version to avoid pod warnings
    scripts:
      - name: Clean
        script: flutter clean
      - name: Install dependencies
        script: flutter pub get
      - name: Pod install
        script: |
          cd ios
          pod install --repo-update
          cd ..
      - name: Build IPA unsigned
        script: flutter build ipa --no-codesign --release
    artifacts:
      - build/ios/ipa/*.ipa
