workflows:
  ios-build:
    name: iOS Codemagic Build
    environment:
      flutter: stable
      xcode: 15.2
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Build iOS
        script: |
          flutter clean
          flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
