workflows:
  development-ipa:
    name: Development IPA (Free Apple Account)
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Set up keychain
        script: |
          keychain initialize
      - name: Install pods
        script: |
          cd ios && pod install && cd ..
      - name: Build IPA (Debug/Profile)
        script: |
          # Use a free provisioning profile (no paid dev account needed)
          flutter build ipa --debug --no-codesign  # or --profile
          
          # Optional: If you need basic signing (for simulator testing)
          # xcodebuild -workspace ios/Runner.xcworkspace -scheme Runner -sdk iphonesimulator -configuration Debug CODE_SIGNING_ALLOWED=NO
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - htikeaung93@gmail.com  # Replace with your email