workflows:
  build-ipa:
    name: Build IPA
    environment:
      flutter: "3.24.4"
      xcode: "15.3"
    scripts:
      - name: Critical Setup
        script: |
          # Set Flutter framework path (essential fix)
          export FLUTTER_ROOT=$HOME/programs/flutter
          mkdir -p ios/Flutter
          cp -r $FLUTTER_ROOT/bin/cache/artifacts/engine/ios-release/Flutter.framework ios/

          # Basic project setup
          flutter clean
          flutter pub get

      - name: Build IPA
        script: |
          flutter build ipa \
            --release \
            --no-codesign \
            --dart-define=CI_BUILD=true \
            --verbose
    artifacts:
      - build/ios/ipa/*.ipa