workflows:
  ios-unsigned-build:
    name: iOS Unsigned Build (Flutter 3.24.4)
    environment:
      flutter: "3.24.4"  # Pinned to your exact version
      xcode: "15.3"      # Recommended for Flutter 3.24.x
      cocoapods: "1.15.2" # Stable version for this setup
    scripts:
      # Phase 1: Project Initialization
      - name: Validate Environment
        script: |
          flutter --version
          dart --version
          xcodebuild -version

      # Phase 2: Dependency Setup
      - name: Get Flutter Dependencies
        script: |
          flutter clean
          flutter pub get
          flutter precache --ios --android

      # Phase 3: iOS-Specific Preparation
      - name: Prepare iOS Environment
        script: |
          cd ios
          pod deintegrate
          pod cache clean --all
          pod repo update
          pod install --verbose
          cd ..
          # Ensure Generated.xcconfig exists
          ls ios/Flutter/Generated.xcconfig || flutter pub get

      # Phase 4: Build Commands (Fixed Format)
      - name: Build Debug IPA
        script: |
          flutter build ipa \
            --debug \
            --no-codesign \
            --dart-define=CI_BUILD=true \
            --verbose

      # Phase 5: Fallback Simulator Build
      - name: Build Simulator Backup
        script: |
          flutter build ios \
            --debug \
            --simulator \
            --no-codesign \
            --dart-define=CI_BUILD=true

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/iphonesimulator/Runner.app
      - flutter_build.log

    publishing:
      email:
        recipients:
          - your.email@example.com
      scripts:
        - name: Archive Build Logs
          script: |
            flutter doctor -v > flutter_doctor.log
            cp $CM_BUILD_LOG flutter_build.log