workflows:
  ios-unsigned:
    name: iOS Unsigned Build
    environment:
      flutter: stable
      xcode: 15.2
      cocoapods: default
    scripts:
      - name: Clean & recreate ios folder
        script: |
          flutter clean
          rm -rf ios/Pods ios/Podfile.lock ios/.symlinks ios/Flutter
          rm -rf ios
          flutter create .
          flutter pub get

      - name: Set iOS deployment target to 13.0
        script: |
          sed -i '' 's/platform :ios, .*/platform :ios, '\''13.0'\''/' ios/Podfile
          sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = .*/IPHONEOS_DEPLOYMENT_TARGET = 13.0;/' ios/Runner.xcodeproj/project.pbxproj

      - name: Install CocoaPods
        script: |
          brew install cocoapods || brew link --overwrite cocoapods
          cd ios
          pod install --repo-update
          cd ..

      - name: Build IPA (unsigned)
        script: flutter build ipa --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
