workflows:
  absolute-ipa-build:
    name: Absolute IPA Build
    environment:
      flutter: "3.24.4"
      xcode: "15.3"
    scripts:
      - name: Complete Environment Reset
        script: |
          # Full cleanup
          flutter clean
          rm -rf ios/Flutter ios/Pods ios/.symlinks
          flutter precache --ios

      - name: Framework & Module Setup
        script: |
          # Recreate Flutter framework structure
          mkdir -p ios/Flutter
          cp -R $FLUTTER_ROOT/bin/cache/artifacts/engine/ios-release/Flutter.framework ios/
          
          # Create modulemap file to fix Swift imports
          echo "framework module Flutter {
            umbrella header 'Flutter.h'
            export *
            module * { export * }
          }" > ios/Flutter/Flutter.framework/Modules/module.modulemap

      - name: Pod Installation
        script: |
          cd ios
          pod deintegrate
          pod cache clean --all
          pod repo update
          pod install --verbose
          cd ..

      - name: Build IPA
        script: |
          flutter build ipa \
            --release \
            --no-codesign \
            --dart-define=CI_BUILD=true \
            --verbose
    artifacts:
      - build/ios/ipa/*.ipa