workflows:
  guaranteed-ipa-build:
    name: Guaranteed IPA Build
    environment:
      flutter: "3.24.4"
      xcode: "15.3"
    scripts:
      - name: Complete iOS Reset
        script: |
          # Backup critical files
          mkdir -p /tmp/ios_backup
          cp -r ios/Runner ios/Flutter ios/Podfile /tmp/ios_backup/
          
          # Nuclear reset
          rm -rf ios/
          flutter create --platforms ios --project-name $(basename $PWD) .
          
          # Restore project files
          cp -r /tmp/ios_backup/Runner ios/
          cp /tmp/ios_backup/Podfile ios/
          rm -rf /tmp/ios_backup

      - name: Framework & Plugin Repair
        script: |
          # Recreate Flutter framework structure
          mkdir -p ios/Flutter
          cp -R $FLUTTER_ROOT/bin/cache/artifacts/engine/ios-release/Flutter.framework ios/
          
          # Force plugin regeneration
          flutter pub get
          cd ios
          pod deintegrate
          pod repo update
          pod install --verbose
          cd ..

      - name: Build IPA
        script: |
          flutter build ipa \
            --release \
            --no-codesign \
            --dart-define=CI_BUILD=true \
            --verbose
    artifacts:
      - build/ios/ipa/*.ipa