workflows:
  build-ipa:
    name: Build IPA
    environment:
      flutter: "3.24.4"
    scripts:
      - name: Build Only
        script: |
          flutter clean
          flutter pub get
          flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa