workflows:
  ios-unsigned:
    name: iOS Unsigned Build
    environment:
      flutter: stable
      xcode: 15.2
      cocoapods: default
    scripts:
      - name: Reinstall CocoaPods with Homebrew
        script: |
          brew uninstall cocoapods || true
          brew install cocoapods
          pod setup
      - name: Clean previous builds
        script: flutter clean
      - name: Get Flutter dependencies
        script: flutter pub get
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          pod install --repo-update
          cd ..
      - name: Build unsigned IPA
        script: flutter build ipa --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
