workflows:
  ios-unsigned:
    name: iOS Unsigned IPA Build
    environment:
      flutter: stable
      xcode: 15.2
    scripts:
      - name: Clean
        script: flutter clean
      - name: Install dependencies
        script: flutter pub get
      - name: Reinstall CocoaPods
        script: |
          sudo gem uninstall cocoapods -a -x || true
          sudo gem install cocoapods -v 1.16.2
      - name: Pod install
        script: |
          cd ios
          pod install --repo-update
          cd ..
      - name: Build IPA unsigned
        script: flutter build ipa --no-codesign --release
    artifacts:
      - build/ios/ipa/*.ipa
