workflows:
  ios-unsigned:
    name: iOS Unsigned Build
    environment:
      flutter: stable
      xcode: 15.2
      cocoapods: default
    scripts:
      - name: Clean Flutter and Pod cache
        script: |
          flutter clean
          flutter pub cache repair || true
          rm -rf ios/Pods ios/Podfile.lock ios/.symlinks ios/Flutter/Flutter.framework
          rm -rf ~/Library/Caches/CocoaPods ~/.cocoapods
          pod cache clean --all || true

      - name: Ensure Flutter SDK and tools are available
        script: |
          flutter pub get
          flutter precache
          flutter doctor -v

      - name: Install CocoaPods with Homebrew
        script: |
          brew uninstall cocoapods || true
          brew install cocoapods
          pod setup

      - name: Pod install clean
        script: |
          cd ios
          pod install --repo-update
          cd ..

      - name: Build unsigned IPA
        script: flutter build ipa --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
