workflows:
  development-ipa:
    name: Development IPA
    environment:
      groups:
        # Add your Apple ID credentials here (Codemagic UI -> Team Settings -> Environment Variables)
        - apple_developer_credentials # Contains APPLE_ID, APPLE_ID_PASSWORD, and FASTLANE_SESSION
      flutter: stable
      xcode: latest
    scripts:
      - name: Set up keychain
        script: |
          keychain initialize
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Build IPA
        script: |
          flutter build ipa --debug # or --profile
          # Alternative using fastlane:
          # flutter packages pub run flutter_launcher_icons:main
          # fastlane build_adhoc
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/flutter_build/logs/*.log
    publishing:
      email:
        recipients:
          - htikeaung93@gmail.com