workflows:
  ios-workflow:
    name: iOS Build Workflow
    environment:
      groups:
        - app_store_credentials
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "com.anycallmobile.anycallmobile_trainingcenter"
    scripts:
      - name: Clean project
        script: |
          flutter clean
          rm -rf ios/Pods ios/Podfile.lock
      - name: Get dependencies
        script: |
          flutter pub get
          cd ios
          pod install --repo-update
          cd ..
      - name: Build IPA
        script: |
          flutter build ipa --release \
            --export-options-plist=ios/ExportOptions.plist \
            --dart-define=FLUTTER_BUILD_MODE=release
    artifacts:
      - build/ios/ipa/*.ipa