workflows:
  ios-workflow:
    name: iOS Build Workflow
    environment:
      groups:
        - app_store_credentials
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "com.anycallmobile.anycallmobile_trainingcenter"
    scripts:
      - name: Clean project
        script: |
          flutter clean
          rm -rf ios/Pods ios/Podfile.lock
      - name: Get dependencies
        script: |
          flutter pub get
          cd ios
          pod install --repo-update
          cd ..
      - name: Build IPA
        script: |
          # Create ExportOptions.plist if missing
          if [ ! -f "ios/ExportOptions.plist" ]; then
            echo '<?xml version="1.0" encoding="UTF-8"?>
            <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
            <plist version="1.0">
            <dict>
                <key>method</key>
                <string>app-store</string>
                <key>uploadBitcode</key>
                <false/>
                <key>uploadSymbols</key>
                <true/>
            </dict>
            </plist>' > ios/ExportOptions.plist
          fi
          
          flutter build ipa --release --export-options-plist=ios/ExportOptions.plist
    artifacts:
      - build/ios/ipa/*.ipa