workflows:
  ios-unsigned:
    name: iOS Unsigned Workflow
    environment:
      flutter: stable
      xcode: 15.2
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Build IPA (unsigned)
        script: flutter build ipa --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
