name: anycallmobile_trainingcenter
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  # android_path_provider:
  audio_video_progress_bar: ^2.0.3
  audioplayers: ^6.1.0
  badges: ^3.0.2
  # better_player: ^0.0.83
  # better_player:
  better_player_plus: ^1.0.7
  cached_network_image: ^3.2.3
  carousel_slider: ^5.0.0
  connectivity_plus: ^6.0.5
  country_code_picker: ^3.0.0
  country_pickers:
  cupertino_icons: ^1.0.2
  device_info_plus:
  file_picker:
  firebase_auth: ^5.3.0
  firebase_core: ^3.5.0
  firebase_messaging:
  flutter:
    sdk: flutter
  flutter_chat_types: ^3.6.0
  flutter_chat_ui: ^1.6.6
  flutter_dotenv: ^5.1.0
  flutter_downloader: ^1.11.1
  flutter_facebook_auth:
  flutter_html: ^3.0.0-alpha.5
  flutter_inappwebview: ^6.0.0
  flutter_local_notifications: ^18.0.1
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.0.10+1
  flutter_switch: ^0.3.2
  fluttertoast: ^8.0.9
  get: ^4.6.5
  get_storage: ^2.0.3
  google_sign_in: ^6.2.1
  http: ^1.0.0
  image_picker: ^1.1.2
  intl:
  json_annotation: ^4.8.0
  modal_bottom_sheet: null
  open_filex: ^4.3.2
  pagination_view: ^2.0.0
  path: ^1.0.0
  # path_provider: ^2.0.11
  permission_handler: ^11.3.1
  phone_number: ^2.1.0
  pin_code_fields: ^8.0.1
  pull_to_refresh: ^2.0.0
  share_plus: null
  shared_preferences: ^2.0.15
  shimmer: ^3.0.0
  shimmer_animation: ^2.1.0+1
  sign_in_with_apple: ^6.1.2
  smooth_page_indicator: ^1.0.0+2
  universal_platform: ^1.0.0+1
  url_launcher: ^6.1.3
  video_thumbnail: ^0.5.3
  youtube_player_flutter: ^9.0.4

dev_dependencies:
  change_app_package_name: ^1.4.0
  flutter_launcher_icons: ^0.14.0
  flutter_lints:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  assets:
    - assets/images/
    - assets/languages/
    - assets/images/notification/
    - assets/logo/
    - assets/images/intro/
    - .env
    - .env.dev
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700
